#!/bin/sh

#Run the code

nodes=100000
edges=1140000

for i in {0..49}
do

./randomgraph $nodes $edges graph/graph$i.txt
../sccfinder/sccfinder graph/graph$i.txt output/output$i.txt

#sleep 1

done

../processoutput/processoutput $nodes